### PR TITLE
Redesigned the website

### PR DESCRIPTION
**Pull request by codewithtyler**
Per issue #12 I redesigned the entire website using ASP.NET 5. Currently that site is up to date on ASP.NET Beta 7. While I was at doing this we changed our SideWaffle release process a bit. Now all future releases will also included creating a release on GitHub. Included in these GitHub releases are the release notes and the template report which are both XML files. The website uses Octokit to pull the content from both of these XML files, parses them, and displays them to the page.

The PR says it can't automatically be merged. I'm guessing that's becauses I removed the old project and created a new one. Please let me know if there's anything that further that I need to do.

### CODE REVIEW

**Comment by RandomlyKnighted** [comment]
One idea @kentcooper had was to have the ```template-report.xml``` contain a Category attribute that would come from where it's located in the "New Project" or "New Item" dialog. For example, if the project template is located under Visual C#\Extensibility then the category would be Extensibility. Then using that information we could continue to have the 3 columns of Project Templates, Item Templates, and Snippets but under each column you'd have a collapsible panels for each of the categories. Inside each panel would be a list of the templates for that category.

I'd like to do this at some point but it looks like we'll have to update TemplateBuilder to do it.

**Comment by RandomlyKnighted** [comment]
@sayedihashimi I've updated the site to use Beta 8 and I've also fixed the merge conflicts.

I'm not quite sure where those last 2 commits came from. They showed up after I rebased the project to remove the merge conflict.

**Comment by RandomlyKnighted** [comment]
@sayedihashimi I'm downloading RC1 now. With my slow internet connection I don't think I'll be finished updating this PR today, but I plan to have it updated to RC1 in the next day or two. Can I get a status update on what the current plan is for getting this merged?

**Comment by RandomlyKnighted** [comment]
Alright this PR has now been updated to RC1.

**Comment by RandomlyKnighted** [comment]
@sayedihashimi did you have any luck with your hosting provider? If I remember correctly the last time we talked you were still waiting on them to get back with you?

**Comment by sayedihashimi** [comment]
@RandomlyKnighted no the pinched nerve set me back on that. Give me a couple more weeks and I should be able to get it working. We do have http://sidewaffle.azurewebsites.net/ which gets pushed with each release.

**Pull request closed without merging**
